### ISSUE TITLE
Create IAM User for everyone

### ISSUE THREAD

**Issue by dinos80152** [gi-khi/investment#1]

**Comment by dinos80152** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As an Admin, I want to access AWS so that we could build infra](https://trello.com/c/tiHcoMwz/1-as-an-admin-i-want-to-access-aws-so-that-we-could-build-infra)

**Comment by kychenzi** [comment]
Create account for dinolai and jimchen. Remind do not push your key to git.
